import "./globals.css";
import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import { QueryProvider } from "@/providers";
import { Toaster } from "@/components/ui";

export const metadata: Metadata = {
  title: "Postify | Your Social Media Management Tool",
  description: "Generated by create next app",
};

const kumbhSans = Kumbh_Sans({
  preload: true,
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kumbhSans.className} antialiased`}>
        <QueryProvider>{children}</QueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
